### ISSUE TITLE
可以分享一个可执行文件吗？

### ISSUE THREAD

**Issue by eyes-clash** [zhlicen/pdgzf#3]
就是用于生成你房源镜像的文件

**Comment by zhlicen** [comment]
https://github.com/zhlicen/pdgzf/releases/tag/rent
上传了可执行文件

**Comment by eyes-clash** [comment]
非常感谢！


Thanks
Best Regards

                       
Original
                       
                     

From:"H. ZHOU"< ***@***.*** &gt;;

Date:2023/6/25 11:12

To:"zhlicen/pdgzf"< ***@***.*** &gt;;

CC:"eyes-clash"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [zhlicen/pdgzf] 可以分享一个可执行文件吗？ (Issue #3)




 
https://github.com/zhlicen/pdgzf/releases/tag/rent
 上传了可执行文件

**Comment by eyes-clash** [comment]
Hi zhou,


      刚发现该程序获取到的公租房房源，少了一个小区（航鹤路1000弄（佳晟里）的房源，如房源ID=186544，
      所以能否把检索房源ID的范围再增加一些？



Thanks,
Best Regards,






李杰
***@***.***







                       
Original
                       
                     

From:"李杰"< ***@***.*** &gt;;

Date:2023/6/25 11:32

To:"zhlicen/pdgzf"< ***@***.*** &gt;;

Subject:Re：Re: [zhlicen/pdgzf] 可以分享一个可执行文件吗？ (Issue #3)


非常感谢！


Thanks
Best Regards

                       
Original
                       
                     

From:"H. ZHOU"< ***@***.*** &gt;;

Date:2023/6/25 11:12

To:"zhlicen/pdgzf"< ***@***.*** &gt;;

CC:"eyes-clash"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [zhlicen/pdgzf] 可以分享一个可执行文件吗？ (Issue #3)




 
https://github.com/zhlicen/pdgzf/releases/tag/rent
 上传了可执行文件
